// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: availability.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailability = `-- name: CreateAvailability :one
INSERT INTO availability (
  doctor_id, day_of_week, start_time, end_time, is_recurring, specific_date
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING availability_id, doctor_id, start_time, end_time, is_recurring, specific_date, created_at, updated_at, day_of_week
`

type CreateAvailabilityParams struct {
	DoctorID     int64
	DayOfWeek    int32
	StartTime    pgtype.Time
	EndTime      pgtype.Time
	IsRecurring  pgtype.Bool
	SpecificDate pgtype.Date
}

func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.DoctorID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.IsRecurring,
		arg.SpecificDate,
	)
	var i Availability
	err := row.Scan(
		&i.AvailabilityID,
		&i.DoctorID,
		&i.StartTime,
		&i.EndTime,
		&i.IsRecurring,
		&i.SpecificDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DayOfWeek,
	)
	return i, err
}
