// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: specialists.sql

package database

import (
	"context"
)

const createSpecialist = `-- name: CreateSpecialist :one
INSERT INTO specialists(user_id,specialization,license_number) VALUES ($1,$2,$3)RETURNING specialist_id, user_id, specialization, license_number
`

type CreateSpecialistParams struct {
	UserID         int64
	Specialization string
	LicenseNumber  string
}

func (q *Queries) CreateSpecialist(ctx context.Context, arg CreateSpecialistParams) (Specialist, error) {
	row := q.db.QueryRowContext(ctx, createSpecialist, arg.UserID, arg.Specialization, arg.LicenseNumber)
	var i Specialist
	err := row.Scan(
		&i.SpecialistID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
	)
	return i, err
}
