// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: specialists.sql

package database

import (
	"context"
)

const createSpecialist = `-- name: CreateSpecialist :one
INSERT INTO specialists(user_id,specialization,license_number) VALUES ($1,$2,$3)RETURNING specialist_id, user_id, specialization, license_number
`

type CreateSpecialistParams struct {
	UserID         int64
	Specialization string
	LicenseNumber  string
}

func (q *Queries) CreateSpecialist(ctx context.Context, arg CreateSpecialistParams) (Specialist, error) {
	row := q.db.QueryRowContext(ctx, createSpecialist, arg.UserID, arg.Specialization, arg.LicenseNumber)
	var i Specialist
	err := row.Scan(
		&i.SpecialistID,
		&i.UserID,
		&i.Specialization,
		&i.LicenseNumber,
	)
	return i, err
}

const getSpecialists = `-- name: GetSpecialists :many
SELECT specialist_id, user_id, specialization, license_number FROM specialists LIMIT $1 OFFSET $2
`

type GetSpecialistsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetSpecialists(ctx context.Context, arg GetSpecialistsParams) ([]Specialist, error) {
	rows, err := q.db.QueryContext(ctx, getSpecialists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialist
	for rows.Next() {
		var i Specialist
		if err := rows.Scan(
			&i.SpecialistID,
			&i.UserID,
			&i.Specialization,
			&i.LicenseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
